# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import os
import sys
import importlib.util

sys.path.insert(0, os.path.abspath("."))


def _has_module(module_name: str) -> bool:
    return importlib.util.find_spec(module_name) is not None


try:
    import robocasa  # type: ignore
except Exception:  # noqa: BLE001
    robocasa = None


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.napoleon",
    "sphinx.ext.mathjax",
    "sphinx.ext.githubpages",
    "sphinx.ext.autodoc",
]

if _has_module("sphinx_markdown_tables"):
    extensions.append("sphinx_markdown_tables")

if _has_module("recommonmark"):
    extensions.append("recommonmark")
elif _has_module("myst_parser"):
    extensions.append("myst_parser")

if _has_module("nbsphinx"):
    extensions.append("nbsphinx")


# Sphinx-apidoc variables
apidoc_module_dir = "../robocasa"
apidoc_output_dir = "reference"


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# source_parsers = {
#     '.md': CommonMarkParser,
# }

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = [".rst"]
if _has_module("recommonmark") or _has_module("myst_parser"):
    source_suffix.append(".md")
if _has_module("nbsphinx"):
    source_suffix.append(".ipynb")

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "RoboCasa"
copyright = "the RoboCasa core team, 2024"
author = "the RoboCasa core team"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = "0.2"
release = "0.2"


# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects htmlstatic_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_book_theme"
html_logo = "robocasa_logo.svg"
html_favicon = "images/Robocasa_web_logo.svg"
html_title = "RoboCasa 0.2 documentation"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "logo": {
        "text": "RoboCasa 0.2 documentation",
    },
}

# Add "Current Version: v1.0" link to the left sidebar (not the page footer).
html_sidebars = {
    "**": [
        "navbar-logo.html",
        "icon-links.html",
        "search-button-field.html",
        "sbt-sidebar-nav.html",
        "sidebar-current-version.html",
    ]
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["images", "static"]

# Custom CSS to match robocasa-main/docs style (clean literals, purple/red code)
html_css_files = ["theme_overrides.css"]

# html_context = {
#     'css_files': [
#         'static/theme_overrides.css',  # override wide tables in RTD theme
#     ],
# }

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "robocasadoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "robocasa.tex", "RoboCasa Documentation", author, "manual"),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "robocasa", "RoboCasa Documentation", [author], 1)]
